/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serveur;

import java.awt.BorderLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;

import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.DateAxis;
import org.jfree.chart.plot.XYPlot;

import org.jfree.data.time.Second;
import org.jfree.data.time.Minute;
import org.jfree.data.time.Hour;
import org.jfree.data.time.Day;
import org.jfree.data.time.Month;
import org.jfree.data.time.Year;
import org.jfree.data.time.TimeSeriesCollection;
import org.jfree.data.time.TimeSeries;
import org.jfree.data.xy.XYDataset;

/**
 *
 * @author bbword
 */
public class Graph_JFrame extends javax.swing.JFrame {

    private SQLDatabaseConnection database;
    private String selection_affichage;

    /**
     * Creates new form Graph_JFrame
     */
    public Graph_JFrame() {
        initComponents();
        this.jRadioButton_minute.setSelected(true);
        this.selection_affichage = "Minutes";
        this.dateDEB_jFormattedTextField.setText("01/01/2021 00:00:10");
        this.dateFIN_jFormattedTextField.setText("31/01/2021 23:59:59");
        this.jPanel_choixDate.repaint();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_tri = new javax.swing.ButtonGroup();
        jPanel_chart = new javax.swing.JPanel();
        jPanel_choixDate = new javax.swing.JPanel();
        jLabel_dateDEB = new javax.swing.JLabel();
        dateDEB_jFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel_dateFIN = new javax.swing.JLabel();
        dateFIN_jFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel_logo = new javax.swing.JLabel();
        jButton_REFRESH = new javax.swing.JButton();
        jPanel_affichage = new javax.swing.JPanel();
        jRadioButton_minute = new javax.swing.JRadioButton();
        jRadioButton_seconde = new javax.swing.JRadioButton();
        jRadioButton_heure = new javax.swing.JRadioButton();
        jRadioButton_annee = new javax.swing.JRadioButton();
        jRadioButton_jour = new javax.swing.JRadioButton();
        jRadioButton_mois = new javax.swing.JRadioButton();
        jLabel_Affichage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("A POSTERIORI");

        jPanel_chart.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel_chartLayout = new javax.swing.GroupLayout(jPanel_chart);
        jPanel_chart.setLayout(jPanel_chartLayout);
        jPanel_chartLayout.setHorizontalGroup(
            jPanel_chartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        jPanel_chartLayout.setVerticalGroup(
            jPanel_chartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        jPanel_choixDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_dateDEB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_dateDEB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_dateDEB.setText("Date de début");

        dateDEB_jFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss"))));
        dateDEB_jFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dateDEB_jFormattedTextField.setToolTipText("Insérer la date de début de la recherche au format JJ/MM/YYYY");
        dateDEB_jFormattedTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dateDEB_jFormattedTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel_dateFIN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_dateFIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_dateFIN.setText("Date de fin");

        dateFIN_jFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss"))));
        dateFIN_jFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dateFIN_jFormattedTextField.setToolTipText("Insérer la date de fin de la recherche au format JJ/MM/YYYY");
        dateFIN_jFormattedTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dateFIN_jFormattedTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/neocampus.png"))); // NOI18N
        jLabel_logo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_logo.setPreferredSize(new java.awt.Dimension(303, 68));

        jButton_REFRESH.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_REFRESH.setText("RAFRAICHIR");
        jButton_REFRESH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_REFRESHActionPerformed(evt);
            }
        });

        jPanel_affichage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup_tri.add(jRadioButton_minute);
        jRadioButton_minute.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_minute.setText("Minutes");
        jRadioButton_minute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_minuteActionPerformed(evt);
            }
        });

        buttonGroup_tri.add(jRadioButton_seconde);
        jRadioButton_seconde.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_seconde.setSelected(true);
        jRadioButton_seconde.setText("Secondes");
        jRadioButton_seconde.setActionCommand("Secondes");
        jRadioButton_seconde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_secondeActionPerformed(evt);
            }
        });

        buttonGroup_tri.add(jRadioButton_heure);
        jRadioButton_heure.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_heure.setText("Heures");
        jRadioButton_heure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_heureActionPerformed(evt);
            }
        });

        buttonGroup_tri.add(jRadioButton_annee);
        jRadioButton_annee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_annee.setText("Années");
        jRadioButton_annee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_anneeActionPerformed(evt);
            }
        });

        buttonGroup_tri.add(jRadioButton_jour);
        jRadioButton_jour.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_jour.setText("Jours");
        jRadioButton_jour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_jourActionPerformed(evt);
            }
        });

        buttonGroup_tri.add(jRadioButton_mois);
        jRadioButton_mois.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_mois.setText("Mois");
        jRadioButton_mois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_moisActionPerformed(evt);
            }
        });

        jLabel_Affichage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Affichage.setText("Affichage par :");

        javax.swing.GroupLayout jPanel_affichageLayout = new javax.swing.GroupLayout(jPanel_affichage);
        jPanel_affichage.setLayout(jPanel_affichageLayout);
        jPanel_affichageLayout.setHorizontalGroup(
            jPanel_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_affichageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Affichage)
                    .addGroup(jPanel_affichageLayout.createSequentialGroup()
                        .addGroup(jPanel_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_heure, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_annee, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_mois, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_minute, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_jour, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_seconde, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_affichageLayout.setVerticalGroup(
            jPanel_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_affichageLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel_Affichage)
                .addGap(18, 18, 18)
                .addGroup(jPanel_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_affichageLayout.createSequentialGroup()
                        .addComponent(jRadioButton_mois, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jRadioButton_minute, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_affichageLayout.createSequentialGroup()
                        .addGroup(jPanel_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_affichageLayout.createSequentialGroup()
                                .addComponent(jRadioButton_annee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_affichageLayout.createSequentialGroup()
                                .addComponent(jRadioButton_jour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton_heure, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_seconde, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_choixDateLayout = new javax.swing.GroupLayout(jPanel_choixDate);
        jPanel_choixDate.setLayout(jPanel_choixDateLayout);
        jPanel_choixDateLayout.setHorizontalGroup(
            jPanel_choixDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_choixDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_choixDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_REFRESH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_affichage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateDEB_jFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateFIN_jFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_dateDEB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_dateFIN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_choixDateLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_choixDateLayout.setVerticalGroup(
            jPanel_choixDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_choixDateLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_choixDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_dateDEB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_choixDateLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(dateDEB_jFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_choixDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_dateFIN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_choixDateLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(dateFIN_jFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel_affichage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_REFRESH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dateDEB_jFormattedTextField.getAccessibleContext().setAccessibleDescription("Insérer la date de début de la recherche au format JJ/MM/YYYY");
        dateFIN_jFormattedTextField.getAccessibleContext().setAccessibleDescription("Insérer la date de fin de la recherche au format JJ/MM/YYYY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_choixDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_choixDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_REFRESHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_REFRESHActionPerformed
        // TODO add your handling code here:

        String chartTitle = "Evolution des capteurs sur une période données";
        String xAxisLabel = "Période d'observation";
        String yAxisLabel = "Valeurs correspondant aux mesures des capteurs";

        XYDataset dataset = createDataset();
        JFreeChart chart = ChartFactory.createTimeSeriesChart(chartTitle, xAxisLabel, yAxisLabel, dataset);

        XYPlot plot = (XYPlot) chart.getPlot();
        DateAxis axis = (DateAxis) plot.getDomainAxis();
        axis.setDateFormatOverride(new SimpleDateFormat("dd-MMM-yyyy HH:mm:ss"));
                
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setMouseWheelEnabled(true);
        this.jPanel_chart.setLayout(new java.awt.BorderLayout());
        this.jPanel_chart.add(chartPanel, BorderLayout.CENTER);
        this.jPanel_chart.validate();

    }//GEN-LAST:event_jButton_REFRESHActionPerformed

    private void jRadioButton_secondeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_secondeActionPerformed
        // TODO add your handling code here:
        this.selection_affichage = this.jRadioButton_seconde.getText();
    }//GEN-LAST:event_jRadioButton_secondeActionPerformed

    private void jRadioButton_anneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_anneeActionPerformed
        // TODO add your handling code here:
        this.selection_affichage = this.jRadioButton_annee.getText();
    }//GEN-LAST:event_jRadioButton_anneeActionPerformed

    private void jRadioButton_moisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_moisActionPerformed
        // TODO add your handling code here:
        this.selection_affichage = this.jRadioButton_mois.getText();
    }//GEN-LAST:event_jRadioButton_moisActionPerformed

    private void jRadioButton_jourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_jourActionPerformed
        // TODO add your handling code here:
        this.selection_affichage = this.jRadioButton_jour.getText();
    }//GEN-LAST:event_jRadioButton_jourActionPerformed

    private void jRadioButton_heureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_heureActionPerformed
        // TODO add your handling code here:
        this.selection_affichage = this.jRadioButton_heure.getText();
    }//GEN-LAST:event_jRadioButton_heureActionPerformed

    private void jRadioButton_minuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_minuteActionPerformed
        // TODO add your handling code here:
        this.selection_affichage = this.jRadioButton_minute.getText();
    }//GEN-LAST:event_jRadioButton_minuteActionPerformed

    private XYDataset createDataset() {

        TimeSeriesCollection dataset = new TimeSeriesCollection();
        TimeSeries series = null;
        String series_name = null;

        try {

            SimpleDateFormat originalFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            SimpleDateFormat targetFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

            Date dateDEB = originalFormat.parse(this.dateDEB_jFormattedTextField.getText());
            Date dateFIN = originalFormat.parse(this.dateFIN_jFormattedTextField.getText());

            System.out.println("Old Format :   " + originalFormat.format(dateDEB));
            System.out.println("New Format :   " + targetFormat.format(dateDEB));

            String sql = "SELECT nom, date, datas "
                    + "FROM capteurs,datas_capteur "
                    + "WHERE capteurs.capteurID = datas_capteur.capteurID "
                    + "AND date BETWEEN '" + targetFormat.format(dateDEB) + "' "
                    + "AND '" + targetFormat.format(dateFIN) + "' "
                    + "ORDER BY nom, date DESC;";
            
            System.out.println("SQL = " + sql);
            
            this.database = new SQLDatabaseConnection();
            Statement st = SQLDatabaseConnection.getStatement();
            ResultSet result = st.executeQuery(sql);

            while (result.next()) {
                if (series_name == null || !series_name.equals(result.getString("nom"))) {
                    //System.out.println("SERIE en cours = " + series_name);
                    if (series_name != null) {
                        //System.out.println("Création de la série = " + series_name);
                        dataset.addSeries(series);
                    }
                    series_name = result.getString("nom");
                    series = new TimeSeries(series_name);
                } else {
                    double data = result.getDouble("datas");                    
                    Timestamp timestampSQL  = (Timestamp) result.getTimestamp("date");
                    Date dateSQL = new Date(timestampSQL.getTime()); 
                    //System.out.println("J'enregistre en date : " + timestampSQL.toString() + " / data : " + data);
                    //System.out.println("J'enregistre en date : " + dateSQL.toString() + " / data : " + data);
                    switch (this.selection_affichage){
                        case "Années":                                
                            series.addOrUpdate(new Year(dateSQL), data);
                            break;
                        case "Mois":                                
                            series.addOrUpdate(new Month(dateSQL), data);
                            break;
                        case "Jours":                                
                            series.addOrUpdate(new Day(dateSQL), data);
                            break;
                        case "Heures":                                
                            series.addOrUpdate(new Hour(dateSQL), data);
                            break;
                        case "Minutes":                                
                            series.addOrUpdate(new Minute(dateSQL), data);
                            break;
                        case "Secondes":                                
                            series.addOrUpdate(new Second(dateSQL), data);
                            break;                            
                        default:                         
                    }                    
                }
            }
            dataset.addSeries(series);
            result.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Graph_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Graph_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Graph_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        return dataset;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graph_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graph_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graph_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graph_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graph_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_tri;
    private javax.swing.JFormattedTextField dateDEB_jFormattedTextField;
    private javax.swing.JFormattedTextField dateFIN_jFormattedTextField;
    private javax.swing.JButton jButton_REFRESH;
    private javax.swing.JLabel jLabel_Affichage;
    private javax.swing.JLabel jLabel_dateDEB;
    private javax.swing.JLabel jLabel_dateFIN;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JPanel jPanel_affichage;
    private javax.swing.JPanel jPanel_chart;
    private javax.swing.JPanel jPanel_choixDate;
    private javax.swing.JRadioButton jRadioButton_annee;
    private javax.swing.JRadioButton jRadioButton_heure;
    private javax.swing.JRadioButton jRadioButton_jour;
    private javax.swing.JRadioButton jRadioButton_minute;
    private javax.swing.JRadioButton jRadioButton_mois;
    private javax.swing.JRadioButton jRadioButton_seconde;
    // End of variables declaration//GEN-END:variables
}
