/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serveur;

import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author bbword
 */
public class Accueil_JFrame extends javax.swing.JFrame {

    private Serveur serveur;

    /**
     * Creates new form Accueil_JFrame
     */
    public Accueil_JFrame(Serveur _serveur) {        
        initComponents();
        this.serveur = _serveur;
        this.jButton_lancer.setEnabled(false);
        
        this.jTextField_host.setText("localhost");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_logo = new javax.swing.JLabel();
        jTextField_port = new javax.swing.JTextField();
        jButton_lancer = new javax.swing.JButton();
        jLabelPort = new javax.swing.JLabel();
        jLabelHost = new javax.swing.JLabel();
        jTextField_host = new javax.swing.JTextField();
        jLabelHost1 = new javax.swing.JLabel();
        jTextField_identifiant = new javax.swing.JTextField();
        jLabelHost2 = new javax.swing.JLabel();
        jPasswordField_passwd = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton_tester = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interface Capteur");
        setResizable(false);

        jLabel_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/neocampus.png"))); // NOI18N
        jLabel_logo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_logo.setPreferredSize(new java.awt.Dimension(303, 68));

        jTextField_port.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jTextField_port.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_port.setText("8952");
        jTextField_port.setToolTipText("Adresse du port d'écoute");
        jTextField_port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_portActionPerformed(evt);
            }
        });

        jButton_lancer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_lancer.setText("Lancer");
        jButton_lancer.setToolTipText("Lancer le serveur");
        jButton_lancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_lancerActionPerformed(evt);
            }
        });

        jLabelPort.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPort.setText("Port :");

        jLabelHost.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelHost.setText("Host :");

        jTextField_host.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jTextField_host.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_host.setText("localhost");
        jTextField_host.setToolTipText("Incriver l'adresse du serveur SQL");
        jTextField_host.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_hostActionPerformed(evt);
            }
        });

        jLabelHost1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelHost1.setText("Identifiant :");

        jTextField_identifiant.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jTextField_identifiant.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_identifiant.setToolTipText("Identifiant du serveur SQL");
        jTextField_identifiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_identifiantActionPerformed(evt);
            }
        });

        jLabelHost2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelHost2.setText("Password :");

        jPasswordField_passwd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_passwd.setToolTipText("Mot de passe de l'utilisateur SQL");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Connexion JDBC");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_tester.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_tester.setText("Tester");
        jButton_tester.setToolTipText("Tester la connexion à la base de données");
        jButton_tester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_testerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPort, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_port, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelHost, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_host, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelHost1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_identifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField_passwd, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jLabelHost2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_tester, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_lancer, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPort, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelHost, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHost1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHost2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_identifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField_passwd))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_lancer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_tester, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_portActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField_portActionPerformed

    private void jButton_lancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_lancerActionPerformed
        if (SQLDatabaseConnection.isOnline) {
            Serveur_IOT_JFrame frame = new Serveur_IOT_JFrame(this.serveur);
            this.serveur.setFrame(frame);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    frame.setVisible(true);
                }
            });
            this.dispose();
        }


    }//GEN-LAST:event_jButton_lancerActionPerformed

    private void jTextField_hostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_hostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_hostActionPerformed

    private void jTextField_identifiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_identifiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_identifiantActionPerformed

    private void jButton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_testerActionPerformed
        try {
            // TODO add your handling code here:        
            Serveur.host = this.jTextField_host.getText();
            Serveur.identifiant = this.jTextField_identifiant.getText();
            Serveur.password = String.valueOf(this.jPasswordField_passwd.getPassword());

            SQLDatabaseConnection database = new SQLDatabaseConnection();
            if (SQLDatabaseConnection.isOnline){
                JOptionPane.showMessageDialog(this,"La connexion à la base de données a réussi.", "Validation de la connexion",JOptionPane.INFORMATION_MESSAGE); 
                this.jButton_lancer.setEnabled(true);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Accueil_JFrame.class.getName()).log(Level.SEVERE, null, ex);                       
        } catch (SQLException ex) {
            //Logger.getLogger(Accueil_JFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"La connexion à la base de données a échoué.", "Erreur de connexion",JOptionPane.ERROR_MESSAGE);     
            System.out.println("je n'ai pas réussi");       
            SQLDatabaseConnection.isOnline = false;
            this.jButton_lancer.setEnabled(false);
        }
    }//GEN-LAST:event_jButton_testerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_lancer;
    private javax.swing.JButton jButton_tester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelHost;
    private javax.swing.JLabel jLabelHost1;
    private javax.swing.JLabel jLabelHost2;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JPasswordField jPasswordField_passwd;
    private javax.swing.JTextField jTextField_host;
    private javax.swing.JTextField jTextField_identifiant;
    private javax.swing.JTextField jTextField_port;
    // End of variables declaration//GEN-END:variables
}
