/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serveur;

import static java.lang.Double.parseDouble;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author valen
 */
public class GestionsCapteur_JFrame extends javax.swing.JFrame {

    private HashMap<String, String> mapCapteur = new HashMap<String, String>();
    private SQLDatabaseConnection database;
    private ArrayList<DefaultMutableTreeNode> rootBatiment = new ArrayList<>();
    private ArrayList<DefaultMutableTreeNode> rootEtage = new ArrayList<>();
    private ArrayList<DefaultMutableTreeNode> leafCapteur = new ArrayList<>();

    /**
     * Creates new form GestionsCapteur_JFrame
     */
    public GestionsCapteur_JFrame() {
        initComponents();
        this.constructTree();
    }

    public void constructTree() {

        try {
            DefaultMutableTreeNode rootCampus = new DefaultMutableTreeNode("néOCampus");
            DefaultTreeModel treeModel = new DefaultTreeModel(rootCampus);

            this.database = new SQLDatabaseConnection();
            Statement st = database.getStatement();
            //--------- Construction du niveau Bâtiment ----------- //
            String sql = "SELECT DISTINCT batiment FROM capteurs ORDER BY batiment ASC;";
            ResultSet rs_bat = st.executeQuery(sql);
            while (rs_bat.next()) {
                DefaultMutableTreeNode rootBatiment = new DefaultMutableTreeNode(rs_bat.getString("batiment"));

                //--------- Construction du niveau Etages ----------- //
                sql = "SELECT DISTINCT etage FROM capteurs WHERE batiment = '" + rs_bat.getString("batiment") + "' ORDER BY etage ASC;";
                ResultSet rs_eta = st.executeQuery(sql);
                while (rs_eta.next()) {
                    DefaultMutableTreeNode rootEtage = new DefaultMutableTreeNode("Etage " + rs_eta.getString("etage"));

                    //--------- Construction du niveau Capteur ----------- //
                    sql = "SELECT DISTINCT nom FROM capteurs "
                            + "WHERE batiment = '" + rs_bat.getString("batiment") + "' "
                            + "AND etage = '" + rs_eta.getString("etage") + "' "
                            + "ORDER BY nom ASC;";

                    ResultSet rs_cap = st.executeQuery(sql);
                    while (rs_cap.next()) {
                        DefaultMutableTreeNode leafCapteur = new DefaultMutableTreeNode(rs_cap.getString("nom"));
                        rootEtage.add(leafCapteur);
                    }
                    rootBatiment.add(rootEtage);
                }
                rootCampus.add(rootBatiment);
            }

            this.jTreeGestionCapteurs.setModel(treeModel);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GestionsCapteur_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GestionsCapteur_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void dataSet() {
        try {
            this.database = new SQLDatabaseConnection();
            Statement st = database.getStatement();
            String sql = "SELECT batiment, etage, nom FROM capteurs;"; //ici, on récupère tous les informations des capteurs qui se sont connecté une fois à notre application
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String K = rs.getString("nom");
                String V = rs.getString("batiment") + "-" + rs.getString("etage");
                this.mapCapteur.put(K, V);
            }
            rs.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GestionsCapteur_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GestionsCapteur_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeGestionCapteurs = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_capteur = new javax.swing.JLabel();
        jLabel_lblCapteur = new javax.swing.JLabel();
        jLabel_lblCapteur1 = new javax.swing.JLabel();
        jLabel_lblCapteur2 = new javax.swing.JLabel();
        jLabel_lblCapteur3 = new javax.swing.JLabel();
        jLabel_lblCapteur4 = new javax.swing.JLabel();
        jLabel_lblCapteur5 = new javax.swing.JLabel();
        jLabel_lblCapteur6 = new javax.swing.JLabel();
        jLabel_capteur_fluide = new javax.swing.JLabel();
        jLabel_capteur_Etage = new javax.swing.JLabel();
        jLabel_capteur_batiment = new javax.swing.JLabel();
        jLabel_capteur_Salle = new javax.swing.JLabel();
        jLabel_capteur_MeasureUnitMin = new javax.swing.JLabel();
        jLabel_capteur_MeasureUnitMax = new javax.swing.JLabel();
        jButtonModifSeuils = new javax.swing.JButton();
        jTextFieldSeuilMax = new javax.swing.JTextField();
        jTextFieldSeuilMin = new javax.swing.JTextField();
        jLabel_logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestions des capteurs");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("UT3");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Bâtiment 1");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Etage 1");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("CapteurA");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("CapteurB");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Etages 2");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Capteurs A");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Capteurs B");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Bâtiment 2");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Etage 2");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Capteur A");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Capteur B");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTreeGestionCapteurs.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreeGestionCapteurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeGestionCapteursMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTreeGestionCapteurs);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Informations du capteur");

        jLabel_capteur.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_capteur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_capteur.setText("/");
        jLabel_capteur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_lblCapteur.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_lblCapteur.setText("Nom :");

        jLabel_lblCapteur1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_lblCapteur1.setText("Bâtiment :");

        jLabel_lblCapteur2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_lblCapteur2.setText("Etage :");

        jLabel_lblCapteur3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_lblCapteur3.setText("Fluide :");

        jLabel_lblCapteur4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_lblCapteur4.setText("Seuil min :");

        jLabel_lblCapteur5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_lblCapteur5.setText("Seuil max :");

        jLabel_lblCapteur6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_lblCapteur6.setText("Salle :");

        jLabel_capteur_fluide.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_capteur_fluide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_capteur_fluide.setText("/");
        jLabel_capteur_fluide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_capteur_Etage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_capteur_Etage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_capteur_Etage.setText("/");
        jLabel_capteur_Etage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_capteur_batiment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_capteur_batiment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_capteur_batiment.setText("/");
        jLabel_capteur_batiment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_capteur_Salle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_capteur_Salle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_capteur_Salle.setText("/");
        jLabel_capteur_Salle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_capteur_MeasureUnitMin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_capteur_MeasureUnitMin.setText("jLabel2");

        jLabel_capteur_MeasureUnitMax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_capteur_MeasureUnitMax.setText("jLabel3");

        jButtonModifSeuils.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonModifSeuils.setText("Modifier ");
        jButtonModifSeuils.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifSeuilsActionPerformed(evt);
            }
        });

        jTextFieldSeuilMax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldSeuilMax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSeuilMax.setText("/");
        jTextFieldSeuilMax.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldSeuilMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSeuilMaxActionPerformed(evt);
            }
        });

        jTextFieldSeuilMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldSeuilMin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSeuilMin.setText("/");
        jTextFieldSeuilMin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldSeuilMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSeuilMinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_lblCapteur, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_lblCapteur1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_lblCapteur3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_lblCapteur2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_lblCapteur4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_lblCapteur5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_lblCapteur6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_capteur_Etage, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_capteur_Salle, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_capteur_batiment, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_capteur_fluide, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_capteur, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextFieldSeuilMin, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_capteur_MeasureUnitMin))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextFieldSeuilMax, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_capteur_MeasureUnitMax)))
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(111, 111, 111))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonModifSeuils, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_lblCapteur)
                    .addComponent(jLabel_capteur))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_lblCapteur3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_lblCapteur1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel_capteur_fluide)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_capteur_batiment)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_capteur_Etage)
                    .addComponent(jLabel_lblCapteur2))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_lblCapteur6)
                    .addComponent(jLabel_capteur_Salle))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_lblCapteur4)
                    .addComponent(jLabel_capteur_MeasureUnitMin)
                    .addComponent(jTextFieldSeuilMin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_lblCapteur5)
                    .addComponent(jLabel_capteur_MeasureUnitMax)
                    .addComponent(jTextFieldSeuilMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButtonModifSeuils, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/neocampus.png"))); // NOI18N
        jLabel_logo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_logo.setPreferredSize(new java.awt.Dimension(303, 68));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeGestionCapteursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeGestionCapteursMouseClicked
        // TODO add your handling code here:
        TreePath tp = jTreeGestionCapteurs.getPathForLocation(evt.getX(), evt.getY());
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) jTreeGestionCapteurs.getLastSelectedPathComponent();
        if (tp != null) {
            System.out.println(tp.getLastPathComponent());
            if (tp.getPathCount() == 4) {
                try {
                    Statement st = database.getStatement();
                    String sql = "SELECT nom, fluide, batiment, etage, salle, tresholdMin, tresholdMax, measureUnit FROM capteurs WHERE nom = '" + tp.getLastPathComponent() + "';";
                    System.out.println("2 = " + tp.getLastPathComponent());
                    ResultSet rs = st.executeQuery(sql);

                    while (rs.next()) {
                        jLabel_capteur.setText((String) rs.getString("nom"));
                        jLabel_capteur_fluide.setText((String) rs.getString("fluide"));
                        jLabel_capteur_batiment.setText((String) rs.getString("batiment"));
                        jLabel_capteur_Etage.setText((String) rs.getString("etage"));
                        jLabel_capteur_Salle.setText((String) rs.getString("salle"));
                        jTextFieldSeuilMin.setText((String) rs.getString("tresholdMin"));
                        jTextFieldSeuilMax.setText((String) rs.getString("tresholdMax"));
                        jLabel_capteur_MeasureUnitMin.setText((String) rs.getString("measureUnit"));
                        jLabel_capteur_MeasureUnitMax.setText((String) rs.getString("measureUnit"));
                        jTextFieldSeuilMin.setEnabled(true);
                        jTextFieldSeuilMax.setEnabled(true);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(GestionsCapteur_JFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jTreeGestionCapteursMouseClicked

    private void jButtonModifSeuilsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifSeuilsActionPerformed
        try {
            // TODO add your handling code here:
            Double treshMin =  parseDouble(jTextFieldSeuilMin.getText());
            Double treshMax = parseDouble(jTextFieldSeuilMax.getText());
            String nom = jLabel_capteur.getText();
            Statement st = database.getStatement();
            String sql = "UPDATE capteurs SET tresholdMin = '" + treshMin + "' , tresholdMax = '"+ treshMax + "' WHERE nom = '" + nom + "';";
            int resUpdate = st.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(GestionsCapteur_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonModifSeuilsActionPerformed

    private void jTextFieldSeuilMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSeuilMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSeuilMaxActionPerformed

    private void jTextFieldSeuilMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSeuilMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSeuilMinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionsCapteur_JFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionsCapteur_JFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionsCapteur_JFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionsCapteur_JFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionsCapteur_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModifSeuils;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_capteur;
    private javax.swing.JLabel jLabel_capteur_Etage;
    private javax.swing.JLabel jLabel_capteur_MeasureUnitMax;
    private javax.swing.JLabel jLabel_capteur_MeasureUnitMin;
    private javax.swing.JLabel jLabel_capteur_Salle;
    private javax.swing.JLabel jLabel_capteur_batiment;
    private javax.swing.JLabel jLabel_capteur_fluide;
    private javax.swing.JLabel jLabel_lblCapteur;
    private javax.swing.JLabel jLabel_lblCapteur1;
    private javax.swing.JLabel jLabel_lblCapteur2;
    private javax.swing.JLabel jLabel_lblCapteur3;
    private javax.swing.JLabel jLabel_lblCapteur4;
    private javax.swing.JLabel jLabel_lblCapteur5;
    private javax.swing.JLabel jLabel_lblCapteur6;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldSeuilMax;
    private javax.swing.JTextField jTextFieldSeuilMin;
    private javax.swing.JTree jTreeGestionCapteurs;
    // End of variables declaration//GEN-END:variables
}
