/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serveur;

import java.util.regex.PatternSyntaxException;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author valen
 */
public class Serveur_IOT_JFrame extends javax.swing.JFrame {

    private Serveur serveur;
    private DefaultTableModel modelSaved;

    /**
     * Creates new form Test_Temps_réel
     */
    public Serveur_IOT_JFrame(Serveur _serveur) {
        initComponents();
        this.serveur = _serveur;
        jTableTempsReel.setAutoCreateRowSorter(true);
        this.modelSaved = (DefaultTableModel) jTableTempsReel.getModel();
    }

    //Ajoute un capteur sur une ligne du tableau 
    public void ajouterCapteur(Object[] _row) {
        this.modelSaved.addRow(_row);
        this.jTableTempsReel.setModel(modelSaved);
        this.jTableTempsReel.repaint();  
        System.out.println("FRAME, Connexion capteur");
    }

    //Envoie la valeur du capteur en continu et l'affiche dans la tableau
    //sur la ligne correspondant au capteur
    public void donneeClient(String _value, String _nomCapteur, boolean _horsLimit) {
        int row = searchRow(_nomCapteur);
        if (row >= 0){
            this.modelSaved.setValueAt(_value, row, 5);
            this.jTableTempsReel.setModel(modelSaved);
            this.jTableTempsReel.repaint();  
        }
    }

    public void deconnecterClient(String _outputString) {
        String[] percept = _outputString.split(" ");
        int row = searchRow(percept[1]);
        if (row >= 0) {
            this.modelSaved.removeRow(row);
            this.jTableTempsReel.setModel(modelSaved);
            this.jTableTempsReel.repaint();
            System.out.println("FRAME, Deconnexion capteur");
        }
    }

    public void updateTab() {

    }

    public int searchRow(String _nomDuCapteur) {
        int row = -1;
        for (int item = 0; item < jTableTempsReel.getRowCount(); item++) {
            if (jTableTempsReel.getValueAt(item, 0).equals(_nomDuCapteur)) {
                row = item;
            }
        }
        return row;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTempsReel = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel_Fluides = new javax.swing.JLabel();
        JComboBox_Fluides = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        JComboBox_Batiments = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel_logo = new javax.swing.JLabel();
        jLabel_ONOFF = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton_online = new javax.swing.JToggleButton();
        jButton_Gestion_des_capteurs = new javax.swing.JButton();
        jButton_quitter = new javax.swing.JButton();
        jButton_A_POSTERIORI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Serveur de gestion IOT");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTableTempsReel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom du Capteurs", "Fluide", "Nom du bâtiment", "Etage", "Pièce", "Valeur Actuelle"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTempsReel);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_Fluides.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel_Fluides.setLabelFor(JComboBox_Fluides);
        jLabel_Fluides.setText("Fluides");

        JComboBox_Fluides.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JComboBox_Fluides.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "EAU", "ELECTRICITE", "AIRCOMPRIME", "TEMPERATURE" }));
        JComboBox_Fluides.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JComboBox_FluidesItemStateChanged(evt);
            }
        });
        JComboBox_Fluides.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBox_FluidesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setLabelFor(JComboBox_Batiments);
        jLabel1.setText("Bâtiment");

        JComboBox_Batiments.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JComboBox_Batiments.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "U1", "U2", "U3", "U4" }));
        JComboBox_Batiments.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JComboBox_BatimentsItemStateChanged(evt);
            }
        });
        JComboBox_Batiments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBox_BatimentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Fluides, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JComboBox_Fluides, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JComboBox_Batiments, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JComboBox_Batiments, JComboBox_Fluides});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Fluides)
                    .addComponent(jLabel1)
                    .addComponent(JComboBox_Fluides, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JComboBox_Batiments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/neocampus.png"))); // NOI18N
        jLabel_logo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_logo.setPreferredSize(new java.awt.Dimension(303, 68));

        jLabel_ONOFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/online_red_64.png"))); // NOI18N
        jLabel_ONOFF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_ONOFF)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_ONOFF)
                    .addComponent(jLabel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jToggleButton_online.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton_online.setText("OFFLINE");
        jToggleButton_online.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton_onlineItemStateChanged(evt);
            }
        });
        jToggleButton_online.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_onlineActionPerformed(evt);
            }
        });

        jButton_Gestion_des_capteurs.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_Gestion_des_capteurs.setText("GESTION DES CAPTEURS");
        jButton_Gestion_des_capteurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Gestion_des_capteursActionPerformed(evt);
            }
        });

        jButton_quitter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_quitter.setText("QUITTER");
        jButton_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_quitterActionPerformed(evt);
            }
        });

        jButton_A_POSTERIORI.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_A_POSTERIORI.setText("A POSTERIORI");
        jButton_A_POSTERIORI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_A_POSTERIORIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton_online)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jButton_A_POSTERIORI)
                .addGap(54, 54, 54)
                .addComponent(jButton_Gestion_des_capteurs)
                .addGap(45, 45, 45)
                .addComponent(jButton_quitter)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton_online)
                    .addComponent(jButton_quitter)
                    .addComponent(jButton_Gestion_des_capteurs)
                    .addComponent(jButton_A_POSTERIORI))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_quitterActionPerformed

        // TODO add your handling code here:
        this.serveur.deconnexion();
        System.exit(0);
    }//GEN-LAST:event_jButton_quitterActionPerformed

    private void jButton_Gestion_des_capteursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Gestion_des_capteursActionPerformed
        // TODO add your handling code here:(
        
        // Test fenêtre déjà ouverte        
        GestionsCapteur_JFrame gestionsCapteur_JFrame = new GestionsCapteur_JFrame();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                gestionsCapteur_JFrame.setVisible(true);
            }
        });         
    }//GEN-LAST:event_jButton_Gestion_des_capteursActionPerformed

    private void jToggleButton_onlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_onlineActionPerformed
        // TODO add your handling code here:       
        
    }//GEN-LAST:event_jToggleButton_onlineActionPerformed

    private void jToggleButton_onlineItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jToggleButton_onlineItemStateChanged
        // TODO add your handling code here:
        if (jToggleButton_online.isSelected()) {
            this.online();
            this.serveur.connexion();        
        } else {
            this.offline();
            this.serveur.deconnexion();
        }
        update_ON_OFF(this.serveur.isOnline());
    }//GEN-LAST:event_jToggleButton_onlineItemStateChanged

    private void JComboBox_BatimentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBox_BatimentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBox_BatimentsActionPerformed

    private void JComboBox_BatimentsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JComboBox_BatimentsItemStateChanged
        // TODO add your handling code here:
        this.filtrer();
    }//GEN-LAST:event_JComboBox_BatimentsItemStateChanged

    private void JComboBox_FluidesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBox_FluidesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBox_FluidesActionPerformed

    private void JComboBox_FluidesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JComboBox_FluidesItemStateChanged
        // TODO add your handling code here:
        this.filtrer();
    }//GEN-LAST:event_JComboBox_FluidesItemStateChanged

    private void jButton_A_POSTERIORIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_A_POSTERIORIActionPerformed
        // TODO add your handling code here:
        Graph_JFrame graph_JFrame = new Graph_JFrame();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                graph_JFrame.setVisible(true);
            }
        });        
    }//GEN-LAST:event_jButton_A_POSTERIORIActionPerformed


    public void filtrer() {

        String filtreFluide = (String) JComboBox_Fluides.getSelectedItem();
        String filtreBatiment = (String) JComboBox_Batiments.getSelectedItem();

        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(this.modelSaved);
        jTableTempsReel.setRowSorter(sorter);
        if (filtreFluide.equals("ALL") && filtreBatiment.equals("ALL")) {
            sorter.setRowFilter(null);
        } else {
            try {
                if (!filtreFluide.equals("ALL")) {
                    sorter.setRowFilter(RowFilter.regexFilter("^(?i)" + filtreFluide, 1));
                }
                if (!filtreBatiment.equals("ALL")) {
                    sorter.setRowFilter(RowFilter.regexFilter("^(?i)" + filtreBatiment, 2));
                }
            } catch (PatternSyntaxException pse) {
                System.out.println("Bad regex pattern");
            }
        }
        jTableTempsReel.repaint();
    }

    public void online() {
        jToggleButton_online.setText("ONLINE");
        //jButton_envoyer.setEnabled(true);
    }

    public void offline() {
        jToggleButton_online.setText("OFFLINE");
        //jButton_envoyer.setEnabled(false);
    }

    private void update_ON_OFF(boolean onoff) {
        if (onoff) {
            this.jLabel_ONOFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/online_green_64.png"))); // NOI18N
        } else {
            this.jLabel_ONOFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/online_red_64.png"))); // NOI18N
        }
        this.jLabel_ONOFF.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JComboBox_Batiments;
    private javax.swing.JComboBox<String> JComboBox_Fluides;
    private javax.swing.JButton jButton_A_POSTERIORI;
    private javax.swing.JButton jButton_Gestion_des_capteurs;
    private javax.swing.JButton jButton_quitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Fluides;
    private javax.swing.JLabel jLabel_ONOFF;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTempsReel;
    private javax.swing.JToggleButton jToggleButton_online;
    // End of variables declaration//GEN-END:variables
}
